---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: srcopsmetrics
  annotations:
    thoth-station.ninja/template-version: 0.1.0
  labels:
    app: srcopsmetrics
spec:
  templates:
    - name: analyse
      inputs:
        parameters:
          - name: "IMAGE_STREAM_REGISTRY"
          - name: "IMAGE_STREAM_NAMESPACE"
          - name: "IMAGE_STREAM_TAG"
          - name: GITHUB_REPOSITORY
          - name: GITHUB_ACCESS_TOKEN
          - name: CEPH_BUCKET
          - name: CEPH_BUCKET_PREFIX
          - name: CEPH_SECRET_KEY
          - name: CEPH_KEY_ID
          - name: PYTHONPATH
      container:
        name: srcopsmetrics
        image: "{{inputs.parameters.IMAGE_STREAM_REGISTRY}}/\
        {{inputs.parameters.IMAGE_STREAM_NAMESPACE}}/\
        {{inputs.parameters.GITHUB_REPOSITORY}}:{{inputs.parameters.IMAGE_STREAM_TAG}}"
        env:
          - name: GITHUB_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: srcopsmetrics
                key: github-access-token
          - name: S3_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                name: srcopsmetrics
                key: host
          - name: CEPH_BUCKET
            valueFrom:
              configMapKeyRef:
                name: srcopsmetrics
                key: bucket
          - name: CEPH_BUCKET_PREFIX
            valueFrom:
              configMapKeyRef:
                name: srcopsmetrics
                key: prefix
          - name: CEPH_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: srcopsmetrics
                key: ceph-secret-key
          - name: CEPH_KEY_ID
            valueFrom:
              secretKeyRef:
                name: srcopsmetrics
                key: ceph-key-id
          - name: PYTHONPATH
            value: "."
        activeDeadlineSeconds: 1800