- project:
    release:
      jobs:
        - upload-pypi-sesheta
    check:
      jobs:
        - "thoth-coala"
    gate:
      jobs:
        - "thoth-coala"
    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
