apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: srcopsmetrics
  annotations:
    thoth-station.ninja/template-version: 0.1.0
  labels:
    app: srcopsmetrics

parameters:
  - name: REPOSITORY
    required: true
    description: GitHub repository whose Health Indicator will be computed
    displayName: inspected GitHub repository

  - description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    name: IMAGE_STREAM_REGISTRY
    value: "docker-registry.default.svc:5000"

  - description: Project the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    value: "dtuchyna-thoth-dev"

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

spec:
  serviceAccountName: argo
  entrypoint: srcopsmetrics-workflow

  inputs:
    parameters:
      - name: REPOSITORY
      - name: GITHUB_ACCESS_TOKEN
      - name: S3_ENDPOINT_URL
      - name: CEPH_BUCKET
      - name: CEPH_BUCKET_PREFIX
      - name: CEPH_SECRET_KEY
      - name: CEPH_KEY_ID
      - name: PYTHONPATH

  templates:
    - name: srcopsmetrics-workflow
      steps:
        - - name: collect-knowledge
            template: analyse

        - - name: process-information
            template: process

    - name: analyse
      container:
        image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/srcopsmetrics:${IMAGE_STREAM_TAG}"
        command: ["srcopsmetrics/cli.py"]
        args: ["-c", "{{inputs.parameters.REPOSITORY}}"]
        env:
          - name: GITHUB_ACCESS_TOKEN
            value: "{{inputs.parameters.GITHUB_ACCESS_TOKEN}}"
          - name: S3_ENDPOINT_URL
            value: "{{inputs.parameters.S3_ENDPOINT_URL}}"
          - name: CEPH_BUCKET
            value: "{{inputs.parameters.CEPH_BUCKET}}"
          - name: CEPH_BUCKET_PREFIX
            value: "{{inputs.parameters}.CEPH_BUCKET_PREFIX}"
          - name: CEPH_SECRET_KEY
            value: "{{inputs.parameters.CEPH_SECRET_KEY}}"
          - name: CEPH_KEY_ID
            value: "{{inputs.parameters.CEPH_KEY_ID}}"
          - name: PYTHONPATH
            value: "."

    - name: process
      container:
        image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/srcopsmetrics:${IMAGE_STREAM_TAG}"
        command: ["srcopsmetrics/cli.py"]
        args: ["-p", "{{inputs.parameters.REPOSITORY}}"]
        env:
          - name: GITHUB_ACCESS_TOKEN
            value: "{{inputs.parameters.GITHUB_ACCESS_TOKEN}}"
          - name: S3_ENDPOINT_URL
            value: "{{inputs.parameters.S3_ENDPOINT_URL}}"
          - name: CEPH_BUCKET
            value: "{{inputs.parameters.CEPH_BUCKET}}"
          - name: CEPH_BUCKET_PREFIX
            value: "{{inputs.parameters}.CEPH_BUCKET_PREFIX}"
          - name: CEPH_SECRET_KEY
            value: "{{inputs.parameters.CEPH_SECRET_KEY}}"
          - name: CEPH_KEY_ID
            value: "{{inputs.parameters.CEPH_KEY_ID}}"
          - name: PYTHONPATH
            value: "."
