apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: srcopsmetrics
  annotations:
    thoth-station.ninja/template-version: 0.1.0
  labels:
    app: srcopsmetrics

spec:
  serviceAccountName: argo
  entrypoint: srcopsmetrics-workflow

  inputs:
    parameters:
      - name: REPOSITORY
      - name: GITHUB_ACCESS_TOKEN
      - name: S3_ENDPOINT_URL
      - name: CEPH_BUCKET
      - name: CEPH_BUCKET_PREFIX
      - name: CEPH_SECRET_KEY
      - name: CEPH_KEY_ID
      - name: PYTHONPATH
      - name: IMAGE_STREAM_REGISTRY
      - name: IMAGE_STREAM_NAMESPACE
      - name: IMAGE_STREAM_NAMESPACE

  templates:
    - name: srcopsmetrics-workflow
      steps:
        - - name: collect-knowledge
            template: analyse

        - - name: process-information
            template: process

    - name: analyse
      container:
        image: "{{inputs.parameters.IMAGE_STREAM_REGISTRY}}/{{inputs.parameters.IMAGE_STREAM_NAMESPACE}}/srcopsmetrics:{{inputs.parameters.IMAGE_STREAM_TAG}}"
        command: ["srcopsmetrics/cli.py"]
        args: ["-c", "{{inputs.parameters.REPOSITORY}}"]
        env:
          - name: GITHUB_ACCESS_TOKEN
            value: "{{inputs.parameters.GITHUB_ACCESS_TOKEN}}"
          - name: S3_ENDPOINT_URL
            value: "{{inputs.parameters.S3_ENDPOINT_URL}}"
          - name: CEPH_BUCKET
            value: "{{inputs.parameters.CEPH_BUCKET}}"
          - name: CEPH_BUCKET_PREFIX
            value: "{{inputs.parameters.CEPH_BUCKET_PREFIX}}"
          - name: CEPH_SECRET_KEY
            value: "{{inputs.parameters.CEPH_SECRET_KEY}}"
          - name: CEPH_KEY_ID
            value: "{{inputs.parameters.CEPH_KEY_ID}}"
          - name: PYTHONPATH
            value: "."

    - name: process
      container:
        image: "{{inputs.parameters.IMAGE_STREAM_REGISTRY}}/{{inputs.parameters.IMAGE_STREAM_NAMESPACE}}/srcopsmetrics:{{inputs.parameters.IMAGE_STREAM_TAG}}"
        command: ["srcopsmetrics/cli.py"]
        args: ["-p", "{{inputs.parameters.REPOSITORY}}"]
        env:
          - name: GITHUB_ACCESS_TOKEN
            value: "{{inputs.parameters.GITHUB_ACCESS_TOKEN}}"
          - name: S3_ENDPOINT_URL
            value: "{{inputs.parameters.S3_ENDPOINT_URL}}"
          - name: CEPH_BUCKET
            value: "{{inputs.parameters.CEPH_BUCKET}}"
          - name: CEPH_BUCKET_PREFIX
            value: "{{inputs.parameters}.CEPH_BUCKET_PREFIX}"
          - name: CEPH_SECRET_KEY
            value: "{{inputs.parameters.CEPH_SECRET_KEY}}"
          - name: CEPH_KEY_ID
            value: "{{inputs.parameters.CEPH_KEY_ID}}"
          - name: PYTHONPATH
            value: "."
