apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: srcopsmetrics
  labels:
    app: srcopsmetrics
  annotations:
    thoth-station.ninja/template-version: 0.1.0
    description: >
      SrcOpsMetrics CronJob, collects data about all projects found
      in AICoE organization and thoth-station repository
    openshift.io/display-name: 'Knowledge Cronjob'
    version: 0.0.1
    tags: srcopsmetrics
    template.openshift.io/long-description: >
      SrcOpsMetrics CronJob, collects data about all projects found
      in AICoE organization and thoth-station repository.
    template.openshift.io/provider-display-name: Red Hat, Inc.
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'srcopsmetrics:latest'
  source:
    git:
      ref: master
      uri: 'https://github.com/AICoE/SrcOpsMetrics.git'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: ENABLE_PIPENV
          value: "1"
        - name: THOTH_ADVISE
          value: "0"
      from:
        kind: ImageStreamTag
        name: 's2i-thoth-ubi8-py36:latest'
        namespace: thoth-test-core
    type: Source
  triggers:
    - type: ConfigChange
