apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    thoth-station.ninja/template-version: 0.7.0
  labels:
    app: srcopsmetrics
  name: srcopsmetrics
spec:
  lookupPolicy:
    local: false
