apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    thoth-station.ninja/template-version: 0.7.0
  labels:
    app: srcopsmetrics
  name: srcopsmetrics
spec:
  template:
    metadata:
      name: srcopsmetrics
    spec:
      containers:
      - name: srcopsmetrics
        image: docker-registry.default.svc:5000/dtuchyna-thoth-dev/srcopsmetrics
        env:
          - name: APP_FILE
            value: ./srcopsmetrics/cli.py
          - name: GITHUB_ACCESS_TOKEN
            value: ""
          - name: THOTH_CEPH_SECRET_KEY
            value: ""
          - name: THOTH_CEPH_KEY_ID
            value: ""
          - name: PYTHONPATH
            value: "."
          - name: PREFIX
            value: data/thoth/dtuchyna
          - name: HOST
            value: https://s3.upshift.redhat.com
          - name: BUCKET
            vale: DH-DEV-DATA
        # command: ["srcopsmetrics/cli.py"]
        # args: ["-cp", "thoth-station/amun-api"]
      restartPolicy: OnFailure