apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: srcopsmetrics
  annotations:
    description: "SrcOpsMetrics"
    openshift.io/display-name: "SrcOpsMetrics"
    version: 0.1.0
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run recommendation logic of Thoth to OpenShift.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    app: srcopsmetrics

objects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      name: "${THOTH_ADVISER_JOB_ID}"
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: scropsmetrics
    spec:
      serviceAccountName: argo
      entrypoint: srcopsmetrics-workflow
      arguments:
        parameters:
          - name: THOTH_ADVISER_JOB_ID
            value: "${THOTH_ADVISER_JOB_ID}"
      templates:
        - name: "srcopsmetrics-workflow"
          templateRef:
            name: "srcopsmetrics-workflow"
            template: "srcopsmetrics-workflow"
          arguments:
            parameters:
              - name: GITHUB_ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: srcopsmetrics
                    key: github-access-token
              - name: S3_ENDPOINT_URL
                valueFrom:
                  configMapKeyRef:
                    name: srcopsmetrics
                    key: host
              - name: CEPH_BUCKET
                valueFrom:
                  configMapKeyRef:
                    name: srcopsmetrics
                    key: bucket
              - name: CEPH_BUCKET_PREFIX
                valueFrom:
                  configMapKeyRef:
                    name: srcopsmetrics
                    key: prefix
              - name: CEPH_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: srcopsmetrics
                    key: ceph-secret-key
              - name: CEPH_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: srcopsmetrics
                    key: ceph-key-id
